name: Release

on:
  push:
    branches:
    - release-**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PWD }}

    - uses: actions/checkout@v4
        
    - name: Build and push operator image
      run: make HUB=quay.io/bmangoen docker-push

    - name: Publish bundle in OperatorHub
      run: make HUB=quay.io/bmangoen bundle
    
    - name: Create GitHub release
      run: make create-gh-release