name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Define the release version"
        required: true
        default: '0.2.0'
  push:
    branches:
      - release-**

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  release:
    if: ${{ github.event_name == 'push' && contains(github.ref_name, "release-") }}
    runs-on: ubuntu-latest

    steps:
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PWD }}

    - uses: actions/checkout@v4
        
    - name: Build and push operator image
      run: make HUB=quay.io/bmangoen docker-push

    - name: Publish bundle in OperatorHub
      run: make -e OPERATOR_VERSION="${VERSION}" -e OWNER=bmangoen -e FORK=bmangoen bundle-publish
    
    - name: Create GitHub release
      run: make -e VERSION="${VERSION}" create-gh-release