name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Define the release version"
        required: true
        default: '0.2.0'

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_EMAIL: ${{ secrets.GIT_EMAIL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PWD }}

    - uses: actions/checkout@v4

    - name: Build and push operator image
      run: make -e HUB=quay.io/bmangoen -e TAG=$VERSION docker-push

    - name: Set git config user
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"

    - name: Publish bundle in OperatorHub
      run: make -e OPERATOR_VERSION=$VERSION -e OWNER=bmangoen -e FORK=bmangoen bundle-publish
    
    - name: Create GitHub release
      run: make -e VERSION=$VERSION create-gh-release