name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Define the release version"
        required: true
        default: '0.2.0'

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  RELEASE_VERSION: ${{ inputs.release_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PWD }}

    - uses: actions/checkout@v4

    - name: Build and push operator image
      run: make docker-push
      env:
        HUB: quay.io/bmangoen
        TAG: $RELEASE_VERSION

    # - name: Publish bundle in OperatorHub
    #   run: make bundle-publish
    #   env:
    #     OPERATOR_VERSION: $RELEASE_VERSION
    #     OWNER: bmangoen
    #     FORK: bmangoen
    
    - name: Create GitHub release
      run: make create-gh-release
      env:
        VERSION: $RELEASE_VERSION