name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
      bundle_channels:
        description: "Bundle channels"
        required: true
        default: "candidates"

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Login to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PWD }}

    - uses: actions/checkout@v4

    - name: Build and push operator image
      run: |
        make docker-push \
          -e HUB=quay.io/bmangoen \
          -e TAG=$VERSION

    - name: Generate bundle metadata
      run: |
        make bundle \
         -e CHANNELS=$CHANNELS
      env:
        CHANNELS: ${{ inputs.bundle_channels }}

    - name: Publish bundle in OperatorHub
      run: |
        make bundle-publish \
          -e OPERATOR_VERSION=$VERSION \
          -e OWNER=bmangoen \
          -e FORK=bmangoen
    
    - name: Create GitHub release
      run: make create-gh-release